import json

import pytest


def test_endpoint(test_app):
    test_request_payload = {'text': 'shoce pq podciy nfwh phfer epgdc'}
    test_response_payload = {
        'prepositions': 0,
        'verbs': 1,
        'subjunctive_verbs': 0,
        'pretty_numbers': 2,
        'vocabulary_list': [
            'shoce',
            'nfwh',
            'podciy',
            'pq',
            'phfer',
            'epgdc']}

    response = test_app.post('/parse', data=json.dumps(test_request_payload),)

    assert response.status_code == 200
    assert response.json() == test_response_payload


def test_case_a(test_app):
    test_request_payload = {'text': 'shoce pq podciy nfwh phfer epgdc dgsloqe do rhfl qhmoixw cmfur qdrulxogji whc ermjdhsx py en yco ienqm wjuln dwuch qinhmjul mjxdqfrnlg iygsex qihmu grewyluhfs ucf us xclpedqmi yrx qinexwo qx rqw wxflpdn rsogxd cpqmxj lgchqdin fdw nwcrus coj nj qplfjnwidg fwdmslqn cwj hysucxdqm ms hdmwpe igxweo sqflo ycqlinro ghu hgecdfj mw xrpmyenq fgixsr fpwcnguieh fclgj ghepqyd jxhwe cejfugn ujxqh ihncrl mlceo udr fm ocxfsjdng sfoqmd pdoymnwxei spqinedf ql ncsepfl icmqsdj chwjlg yiq ifl syejrqd lwnepmcg xlmnfqry ghlyopuncw qx iw sionpux cop dmqpchuyf ojxfqhernm ignpeyf rseoyl emjocsild rfimdy mwd oewgjfr uo irmcunfgx ylduwpsnh xrdng gcxr ng prfmjicud srdueqhgiy nmodwsqijh dcnql'}
    test_response_payload = {
        'prepositions': 3,
        'verbs': 36,
        'subjunctive_verbs': 25,
        'pretty_numbers': 22,
        'vocabulary_list': [
            'sqflo',
            'spqinedf',
            'sfoqmd',
            'syejrqd',
            'shoce',
            'srdueqhgiy',
            'sionpux',
            'xclpedqmi',
            'xlmnfqry',
            'xrpmyenq',
            'xrdng',
            'ocxfsjdng',
            'oewgjfr',
            'ojxfqhernm',
            'cop',
            'coj',
            'cmfur',
            'cwj',
            'cpqmxj',
            'chwjlg',
            'cejfugn',
            'qx',
            'qplfjnwidg',
            'qhmoixw',
            'ql',
            'qdrulxogji',
            'qinhmjul',
            'qinexwo',
            'qihmu',
            'ncsepfl',
            'nmodwsqijh',
            'nwcrus',
            'nfwh',
            'nj',
            'ng',
            'ms',
            'mw',
            'mwd',
            'mlceo',
            'mjxdqfrnlg',
            'wxflpdn',
            'whc',
            'wjuln',
            'podciy',
            'pq',
            'py',
            'phfer',
            'prfmjicud',
            'pdoymnwxei',
            'fclgj',
            'fm',
            'fwdmslqn',
            'fpwcnguieh',
            'fdw',
            'fgixsr',
            'yco',
            'ycqlinro',
            'ylduwpsnh',
            'yrx',
            'yiq',
            'hysucxdqm',
            'hdmwpe',
            'hgecdfj',
            'en',
            'emjocsild',
            'epgdc',
            'ermjdhsx',
            'lwnepmcg',
            'lgchqdin',
            'jxhwe',
            'rsogxd',
            'rseoyl',
            'rqw',
            'rfimdy',
            'rhfl',
            'do',
            'dcnql',
            'dmqpchuyf',
            'dwuch',
            'dgsloqe',
            'gcxr',
            'ghepqyd',
            'ghlyopuncw',
            'ghu',
            'grewyluhfs',
            'us',
            'uo',
            'ucf',
            'ujxqh',
            'udr',
            'icmqsdj',
            'iw',
            'ifl',
            'iygsex',
            'ihncrl',
            'ienqm',
            'irmcunfgx',
            'igxweo',
            'ignpeyf']}

    response = test_app.post('/parse', data=json.dumps(test_request_payload),)

    assert response.status_code == 200
    assert response.json() == test_response_payload


def test_case_b(test_app):
    test_request_payload = {'text': 'dufqwh ndis eqclrnguo ceqrugs meod eofxlrd uqpwmni xrhm qgro hlwgimn fjnomcledi silruxh efwh uxfrpsnqd fyejhi fxdn swfruc eopq hcgeox lhimoynsr rwjxecpmfl gimqxwuyr eujh rfs qncuyiel hwuiqlne umyldn uwflpqc gywlc oxmegsdi sqemywlg cnfimrgows hnxyfd exmdnos djpsogiy xyp myngercj yeujqcoih sgljco xy lruneodc frqog hqsgcy wmi hyfgqj iecusqjp ugnmqfypsd yp rxoew lqeshijndg umynehjsci rnc xhrjyocde mnefpj rcyihwxq oihjwrup gquscxhw ucrfdsoeq drg nqhodjsm snp cwoen ehyldsnmf pmrs cghuwpfxly ifwpnx wqdgrl xocpjedsfm oegli url rylnsph ijucmxw jwispgefdo heixgmcy gm sdhfnoxg hc jqwpdo eo hmypjfu xuedl nqpge cnyosu dniefl lf xcdupho wixmhcuynj poy ous jwroheqm xchm jnufdshiqe liyrexhmu cjlxoiquef fwqrijemcd csxpy eqxghfry fhnwomgyuq yj euhxmosc'}

    test_response_payload = {
        'prepositions': 3,
        'verbs': 46,
        'subjunctive_verbs': 26,
        'pretty_numbers': 21,
        'vocabulary_list': [
            'sqemywlg',
            'snp',
            'swfruc',
            'sdhfnoxg',
            'sgljco',
            'silruxh',
            'xocpjedsfm',
            'xchm',
            'xcdupho',
            'xy',
            'xyp',
            'xhrjyocde',
            'xrhm',
            'xuedl',
            'oxmegsdi',
            'oegli',
            'ous',
            'oihjwrup',
            'csxpy',
            'cnfimrgows',
            'cnyosu',
            'cwoen',
            'ceqrugs',
            'cjlxoiquef',
            'cghuwpfxly',
            'qncuyiel',
            'qgro',
            'nqpge',
            'nqhodjsm',
            'ndis',
            'mnefpj',
            'myngercj',
            'meod',
            'wqdgrl',
            'wmi',
            'wixmhcuynj',
            'poy',
            'pmrs',
            'fxdn',
            'fwqrijemcd',
            'fyejhi',
            'fhnwomgyuq',
            'fjnomcledi',
            'frqog',
            'yp',
            'yeujqcoih',
            'yj',
            'hc',
            'hcgeox',
            'hqsgcy',
            'hnxyfd',
            'hmypjfu',
            'hwuiqlne',
            'hyfgqj',
            'heixgmcy',
            'hlwgimn',
            'exmdnos',
            'eo',
            'eopq',
            'eofxlrd',
            'eqxghfry',
            'eqclrnguo',
            'efwh',
            'ehyldsnmf',
            'euhxmosc',
            'eujh',
            'lqeshijndg',
            'lf',
            'lhimoynsr',
            'lruneodc',
            'liyrexhmu',
            'jqwpdo',
            'jnufdshiqe',
            'jwroheqm',
            'jwispgefdo',
            'rxoew',
            'rcyihwxq',
            'rnc',
            'rwjxecpmfl',
            'rfs',
            'rylnsph',
            'dniefl',
            'djpsogiy',
            'drg',
            'dufqwh',
            'gquscxhw',
            'gm',
            'gywlc',
            'gimqxwuyr',
            'uxfrpsnqd',
            'ucrfdsoeq',
            'uqpwmni',
            'umynehjsci',
            'umyldn',
            'uwflpqc',
            'url',
            'ugnmqfypsd',
            'ifwpnx',
            'iecusqjp',
            'ijucmxw']}

    response = test_app.post('/parse', data=json.dumps(test_request_payload),)

    assert response.status_code == 200
    assert response.json() == test_response_payload
